 -- EXERCICIO 3:
-- UTILIZA LISTAGG PARA SEPARAR O NOME DOS FORNECEDORES POR , PARA EXIBIT O NOME DOS FORNECEDORES DO PRODUTO
-- SUM PARA CALCULAR AS QUANTIDADES
-- JOIN NA TABELA PRODUTO PARA EXIBIR AS INFORMACOES DO P E AGRUPAMENTO
-- JOIN NA TABALEA DE FORNECEDORES PARA EXIBIR O NOME DOS FORNECEDORES
SELECT 
    p.cod_produto,
    p.nome AS nome_produto,
    p.preco,
    LISTAGG(f.nome, ', ') WITHIN GROUP (ORDER BY f.nome) AS nome_fornecedor,
    SUM(pf.quantidade) AS quantidade_total
FROM 
    PRODUTO_FORNECEDOR pf
JOIN 
    PRODUTO p ON pf.cod_produto = p.cod_produto
JOIN 
    FORNECEDOR f ON pf.cod_fornecedor = f.cod_fornecedor
GROUP BY 
    p.cod_produto, p.nome, p.preco
ORDER BY 
    p.cod_produto;

-- A2 --
-- a:
-- UTILIZA FUNCAO SOMA PARA CALCULAR A SOMA DA QUANTIDADE E VALOR UNITARIO DE TODOS PEDIDOS RELIZADOS NA TABELA ASSOCIATIVA
-- JOIN NA TABELA PEDIDO PARA PEGAR OS PEDIDOS DO CLIENTE
-- JOIN NA TABELA PRODUTO PARA PEGAR O NOME DO PRODUTO
-- SOMA TODAS QUANTIDADES X VALOR UNITARIO COMO TOTAL
-- CONDICAO FINAL ONDE O TOTAL DEVE SER 1000
SELECT 
    ip.NUM_PEDIDO, 
    prod.COD_PRODUTO, 
    prod.NOME AS NOME_PRODUTO, 
    c.NOME AS NOME_CLIENTE,
    SUM(ip.QUANTIDADE * ip.VALOR_UNITARIO) AS TOTAL
FROM 
    ITEM_PEDIDO ip
JOIN 
    PEDIDO ped ON ped.NUM_PEDIDO = ip.NUM_PEDIDO
JOIN 
    CLIENTE c ON c.COD_CLIENTE = ped.COD_CLIENTE
JOIN 
    PRODUTO prod ON prod.COD_PRODUTO = ip.COD_PRODUTO
GROUP BY 
    ip.NUM_PEDIDO, 
    prod.COD_PRODUTO, 
    prod.NOME, 
    c.NOME
HAVING 
    SUM(ip.QUANTIDADE * ip.VALOR_UNITARIO) > 1000;

    
-- b:
-- SELECIONA OS CLIENTES PESSOA_FISICA
-- JOIN NA TABELA DE CLIENTE APENAS PARA MOSTRAR O NOME DOS CLIENTES
-- JOIN NA TABELA PESSOA_JURIDICA PARA PEGAR A RAZAO SOCIAL DA EMPRESA DA PF
SELECT c.NOME, pf.COD_CLIENTE, pf.CPF, pf.COD_EMPRESA, pj.RAZAO_SOCIAL
FROM PESSOA_FISICA pf
JOIN 
    CLIENTE c ON c.COD_CLIENTE = pf.COD_CLIENTE
JOIN 
    PESSOA_JURIDICA pj ON pf.COD_EMPRESA = pj.COD_CLIENTE

--c:
-- APENAS CATEGORIAS COM COD_CATEGORIA_PAI SENDO NULOS
-- JOIN NA TABELA DE PRODUTO PARA AGRUPAR OS PRODUTOS POR CATEGORIA E CODIGO
-- UTILIZA FUNCAO COUNT
SELECT 
cat.COD_CATEGORIA, 
cat.NOME, 
COUNT(p.COD_PRODUTO) AS QUANTIDADE_PRODUTOS
FROM 
    CATEGORIA cat
JOIN 
    PRODUTO p ON p.COD_CATEGORIA = cat.COD_CATEGORIA
WHERE 
    cat.COD_CATEGORIA_PAI IS NULL
GROUP BY 
    cat.COD_CATEGORIA, 
    cat.NOME;

-- d:
-- AGRUPA AS CATEGORIAS PELO CODIGO E NOME
-- JOIN NA TABELA DE CATEGORIA PARA MOSTRAR O NOME
-- UTILIZA FUNCAO AVG E COUNT PARA MEDIA E TOTAL
SELECT 
c.COD_CATEGORIA, 
c.NOME AS NOME_CATEGORIA, 
COUNT(p.COD_PRODUTO) AS TOTAL_PRODUTOS, 
AVG(p.PRECO) AS MEDIA_PRECO
FROM 
    PRODUTO p
JOIN 
    CATEGORIA c ON c.COD_CATEGORIA = p.COD_CATEGORIA
WHERE
    p.IMPORTADO = 'S'
GROUP BY 
    c.COD_CATEGORIA, 
    c.NOME
ORDER BY 
    MEDIA_PRECO DESC;


-- e:
-- AGRUPA OS PRODUTOS PELO CODIGO E NOME DO PRODUTO
-- JOIN NA TABELA DE PRODUTOS APENAS PARA MOSTRAR O NOME DO PRODUTO
SELECT 
p.NOME,
ip.COD_PRODUTO,
SUM(ip.QUANTIDADE) AS TOTAL_VENDIDO
FROM 
    ITEM_PEDIDO ip
JOIN
    PRODUTO p ON  p.COD_PRODUTO = ip.COD_PRODUTO
GROUP BY 
    ip.COD_PRODUTO,
    P.NOME
ORDER BY 
    TOTAL_VENDIDO DESC
FETCH FIRST 5 ROWS ONLY;
